<?php
require __DIR__.'/../app.php';
header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');
if(!is_dir($storage.'/sessions')) mkdir($storage.'/sessions',0700,true);
session_save_path($storage.'/sessions');
session_set_cookie_params(['httponly'=>true,'samesite'=>'Strict','secure'=>!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off']);session_start();
$_SESSION['csrf']??=bin2hex(random_bytes(24));
$a=$_GET['action']??'state';$post=$_SERVER['REQUEST_METHOD']==='POST';
if($post && !hash_equals($_SESSION['csrf'],$_SERVER['HTTP_X_CSRF_TOKEN']??''))fail('Session check failed. Refresh and retry.',403);
$in=$post?(str_contains($_SERVER['CONTENT_TYPE']??'','application/json')?json_decode(file_get_contents('php://input'),true):$_POST):$_GET;
$in=is_array($in)?$in:[];
try {
if($a==='session'){$out=['csrf'=>$_SESSION['csrf'],'verification'=>$releaseCheck!==null,'user'=>isset($_SESSION['uid'])?array_diff_key(currentUser(),array_flip(['password','units'])):null];}
elseif($a==='login'&&$post){$ip=$_SERVER['REMOTE_ADDR']??'local';$attempt=q('SELECT * FROM attempts WHERE ip=?',[$ip])->fetch(PDO::FETCH_ASSOC);if($attempt&&$attempt['count']>=10&&time()-$attempt['at']<300)fail('Too many attempts. Try again in five minutes.',429);$u=q('SELECT * FROM users WHERE username=? AND active=1',[$in['username']??''])->fetch(PDO::FETCH_ASSOC);if(!$u||!accountPassword($in['password']??'',$u['password'])){q('INSERT INTO attempts VALUES(?,1,?) ON CONFLICT(ip) DO UPDATE SET count=CASE WHEN at<? THEN 1 ELSE count+1 END,at=?',[$ip,time(),time()-300,time()]);fail('Incorrect login.',401);}q('DELETE FROM attempts WHERE ip=?',[$ip]);session_regenerate_id(true);$_SESSION['uid']=$u['id'];$out=['ok'=>true];}
else {
$u=currentUser();
if($u['force_change']&& !in_array($a,['session','logout','state','change-password'],true))fail('Change your initial password first.',403);
if($a==='state'&&$u['force_change']){header('Content-Type: application/json');echo json_encode(['forceChange'=>true,'csrf'=>$_SESSION['csrf']]);exit;}
if($a==='logout'&&$post){$_SESSION=[];session_destroy();$out=['ok'=>true];}
elseif($a==='change-password'&&$post){$password=(string)($in['password']??'');if(strlen($password)<12||strlen($password)>256)fail('Choose a password of 12 to 256 characters.');if(accountPassword($password,$u['password']))fail('Choose a different password.');q('UPDATE users SET password=?,force_change=0 WHERE id=?',[password_hash($password,PASSWORD_DEFAULT),$u['id']]);audit(null,(int)$u['id'],'Password changed');session_regenerate_id(true);$out=['ok'=>true];}
elseif($a==='state'||$a==='export'){
$requests=[];foreach(q('SELECT id FROM requests ORDER BY id DESC')->fetchAll(PDO::FETCH_COLUMN) as $id){$r=q('SELECT unit,requester FROM requests WHERE id=?',[$id])->fetch(PDO::FETCH_ASSOC);if(scope($u,(int)$r['unit'])&&($u['role']!=='Requester'||$u['reports']||(int)$r['requester']===(int)$u['id']))$requests[]=projected($u,viewRequest($u,(int)$id));}
if($a==='export'){if(!$u['reports'])fail('Report access required.',403);header('Content-Type: text/csv');header('Content-Disposition: attachment; filename="incentive-report.csv"');$f=fopen('php://output','w');$keys=['id','employee_name','code','unit','department_name','month','reason','status','received'];if(money($u)){$keys[]='amount_inr';foreach($requests as &$row)$row['amount_inr']=$row['amount']===null?'':number_format($row['amount']/100,2,'.','');unset($row);}fputcsv($f,$keys);foreach($requests as $r)fputcsv($f,array_map(fn($k)=>preg_match('/^[=+@\-\t\r]/',(string)($r[$k]??''))?"'".$r[$k]:($r[$k]??''),$keys));exit;}
$employees=array_values(array_filter(q('SELECT e.*,d.name department_name FROM employees e JOIN departments d ON d.id=e.department')->fetchAll(PDO::FETCH_ASSOC),fn($e)=>scope($u,(int)$e['unit'])));
$month=$_GET['month']??date('Y-m');$top=[];foreach(q('SELECT e.name,e.code,r.unit,d.name department,COUNT(*) awards,GROUP_CONCAT(r.reason," | ") reasons,MAX(r.received) received FROM requests r JOIN employees e ON e.id=r.employee JOIN departments d ON d.id=r.department WHERE r.status="Processed" AND r.month=? GROUP BY r.employee,r.unit,r.department ORDER BY SUM(r.amount) DESC,e.name',[$month])->fetchAll(PDO::FETCH_ASSOC) as $r)if(scope($u,(int)$r['unit']))$top[]=$r;
$publicUser=array_diff_key($u,array_flip(['password']));$publicUser['units']=json_decode($u['units'],true);
$out=['user'=>$publicUser,'requests'=>$requests,'employees'=>$employees,'departments'=>q('SELECT * FROM departments')->fetchAll(PDO::FETCH_ASSOC),'top'=>$top,'month'=>$month,'canMoney'=>money($u),'csrf'=>$_SESSION['csrf'],'stages'=>queueSummary($u),'demo'=>getenv('INCENTIVE_DEMO')==='1'];if($u['role']==='Admin')$out['users']=q('SELECT id,username,name,role,units,reports,active FROM users')->fetchAll(PDO::FETCH_ASSOC);
}
elseif($a==='queue'){$stage=(string)($in['stage']??'');$out=['stage'=>$stage,'requests'=>queueRows($u,$stage)];}
elseif($a==='detail'){$r=viewRequest($u,(int)$in['id']);$out=['request'=>projected($u,$r),'audit'=>q('SELECT a.event,a.at,u.name actor FROM audit a JOIN users u ON u.id=a.actor WHERE request=? ORDER BY a.id',[$r['id']])->fetchAll(PDO::FETCH_ASSOC),'files'=>q('SELECT id,type,visibility FROM files WHERE request=?'.(money($u)?'':' AND visibility="approval"'),[$r['id']])->fetchAll(PDO::FETCH_ASSOC)];}
elseif($a==='download'){$f=q('SELECT * FROM files WHERE id=?',[(int)$in['id']])->fetch(PDO::FETCH_ASSOC);if(!$f)fail('File not found.',404);if(!canFile($u,$f))fail('Financial files are restricted to CEO and HR Head.',403);viewRequest($u,(int)$f['request']);header('Content-Type: application/octet-stream');header('Content-Disposition: attachment; filename="supporting-data.'.$f['type'].'"');readfile($storage.'/uploads/'.$f['path']);exit;}
elseif($a==='create'&&$post){if($u['role']!=='Requester')fail('Requester role required.',403);$e=q('SELECT * FROM employees WHERE id=?',[(int)($in['employee']??0)])->fetch(PDO::FETCH_ASSOC);if(!$e||!scope($u,(int)$e['unit']))fail('Employee or unit unavailable.',403);$month=$in['month']??'';if(!preg_match('/^20\d\d-(0[1-9]|1[0-2])$/',$month))fail('Invalid incentive month.');$reason=clean($in['reason']??'',2000);
$uploads=[];foreach(['file'=>'private','evidence'=>'approval'] as $field=>$visibility){$file=$_FILES[$field]??null;$path=null;$ext=null;if($file&&$file['error']!==UPLOAD_ERR_NO_FILE){if($file['error']!==UPLOAD_ERR_OK||$file['size']>5*1024*1024)fail('Upload must be at most 5 MB.');$ext=strtolower(pathinfo($file['name'],PATHINFO_EXTENSION));if(!in_array($ext,['pdf','csv','txt','xlsx','png','jpg','jpeg'],true))fail('Unsupported file type.');$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$allowed=['pdf'=>['application/pdf'],'csv'=>['text/plain','text/csv','application/csv'],'txt'=>['text/plain'],'xlsx'=>['application/zip','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],'png'=>['image/png'],'jpg'=>['image/jpeg'],'jpeg'=>['image/jpeg']];if(!in_array($mime,$allowed[$ext],true))fail('File content does not match its type.');if($visibility==='approval'&&empty($in['evidence_confirm']))fail('Confirm approval evidence contains no incentive amounts.');$path=bin2hex(random_bytes(20));if(!move_uploaded_file($file['tmp_name'],$storage.'/uploads/'.$path))fail('Upload could not be saved.',500);}
if($path)$uploads[]=[$path,$ext,$visibility];}
$db->beginTransaction();q('INSERT INTO requests(employee,unit,department,month,reason,requester,status,created) VALUES(?,?,?,?,?,?,?,?)',[$e['id'],$e['unit'],$e['department'],$month,$reason,$u['id'],'Plant Head',date('c')]);$id=(int)$db->lastInsertId();foreach($uploads as [$path,$ext,$visibility])q('INSERT INTO files(request,path,type,visibility) VALUES(?,?,?,?)',[$id,$path,$ext,$visibility]);audit($id,(int)$u['id'],'Requested');$db->commit();$out=['id'=>$id];}
elseif($a==='transition'&&$post){$db->beginTransaction();$r=viewRequest($u,(int)$in['id']);$action=$in['decision']??'';$next=null;$amount=$r['amount'];$received=$r['received'];if($r['status']==='Plant Head'&&$u['role']==='Plant Head'&&in_array($action,['approve','reject'])){$next=$action==='approve'?'CEO':'Rejected';$event=$action==='approve'?'Plant approved':'Plant rejected';}elseif($r['status']==='CEO'&&$u['role']==='CEO'&&in_array($action,['approve','reject'])){$next=$action==='approve'?'HR Value':'Rejected';$event=$action==='approve'?'CEO approved':'CEO rejected';}elseif($r['status']==='HR Value'&&$u['role']==='HR Head'&&$action==='assign'){$v=(string)($in['amount']??'');if(!preg_match('/^\d{1,8}(\.\d{1,2})?$/',$v)||(float)$v<=0)fail('Enter a positive amount with at most two decimals.');$amount=(int)round((float)$v*100);$next='HR Processing';$event='Amount assigned';}elseif($r['status']==='HR Processing'&&$u['role']==='HR Head'&&in_array($action,['Processed','Not Processed'])){$next=$action;$event=$action;if($action==='Processed')$received=date('c');}else fail('This role cannot perform that action at this stage.',403);q('UPDATE requests SET status=?,amount=?,received=? WHERE id=?',[$next,$amount,$received,$r['id']]);audit((int)$r['id'],(int)$u['id'],$event);$db->commit();$out=['ok'=>true];}
elseif($a==='department'&&$post){if($u['role']!=='Admin')fail('Admin required.',403);$name=clean($in['name']??'');if(!empty($in['id']))q('UPDATE departments SET name=? WHERE id=?',[$name,(int)$in['id']]);else q('INSERT INTO departments(name) VALUES(?)',[$name]);audit(null,(int)$u['id'],'Department saved');$out=['ok'=>true];}
elseif($a==='employee'&&$post){if($u['role']!=='Admin')fail('Admin required.',403);$unit=(int)($in['unit']??0);if(!in_array($unit,[1,2,3])||!scope($u,$unit)||!q('SELECT id FROM departments WHERE id=?',[(int)$in['department']])->fetchColumn())fail('Invalid unit or department.');$args=[clean($in['code']??''),clean($in['name']??''),$unit,(int)$in['department']];if(!empty($in['id'])){$old=q('SELECT unit FROM employees WHERE id=?',[(int)$in['id']])->fetchColumn();if(!$old||!scope($u,(int)$old))fail('Unit access denied.',403);$args[]=(int)$in['id'];q('UPDATE employees SET code=?,name=?,unit=?,department=? WHERE id=?',$args);}else q('INSERT INTO employees(code,name,unit,department) VALUES(?,?,?,?)',$args);audit(null,(int)$u['id'],'Employee saved');$out=['ok'=>true];}
elseif($a==='user'&&$post){if($u['role']!=='Admin')fail('Admin required.',403);$role=$in['role']??'';$units=array_values(array_unique(array_map('intval',$in['units']??[])));if(!in_array($role,['Admin','Requester','Plant Head','CEO','HR Head'])||!$units||array_diff($units,[1,2,3]))fail('Invalid role or units.');$id=(int)($in['id']??0);$old=$id?q('SELECT * FROM users WHERE id=?',[$id])->fetch(PDO::FETCH_ASSOC):null;if($id&&!$old)fail('User not found.');if($id===(int)$u['id']&&($role!=='Admin'||empty($in['active'])))fail('Keep your own Admin account active.');$args=[clean($in['username']??''),clean($in['name']??''),$role,json_encode($units),!empty($in['reports'])?1:0,!empty($in['active'])?1:0];$password=$in['password']??'';if((!$old||$password!=='')&&strlen($password)<12)fail('Password requires at least 12 characters.');if($old){$args[]=$id;q('UPDATE users SET username=?,name=?,role=?,units=?,reports=?,active=? WHERE id=?',$args);if($password!=='')q('UPDATE users SET password=? WHERE id=?',[password_hash($password,PASSWORD_DEFAULT),$id]);}else{q('INSERT INTO users(username,name,role,units,reports,active,password) VALUES(?,?,?,?,?,?,?)',[...$args,password_hash($password,PASSWORD_DEFAULT)]);}audit(null,(int)$u['id'],'User access saved');$out=['ok'=>true];}
else fail('Unknown action.',404);
}
header('Content-Type: application/json');echo json_encode($out,JSON_UNESCAPED_UNICODE);
} catch(Throwable $e){if($db->inTransaction())$db->rollBack();fail($e instanceof PDOException?'Could not save. Check for duplicate codes or usernames.':'Unable to complete request.',400);}
